# Generated by Django 4.0.6 on 2022-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HueyKv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.TextField(default='default')),
                ('key', models.TextField(blank=True, null=True)),
                ('value', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HueySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.TextField(default='default')),
                ('data', models.BinaryField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={'ordering': ('timestamp',)},
        ),
        migrations.CreateModel(
            name='HueyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.TextField(default='default')),
                ('data', models.BinaryField(blank=True, null=True)),
                ('priority', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={'ordering': ('-priority', 'id')},
        ),
    ]
